version: '3.8'

services:
  django:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
